name: Deploy AWS Lambda
on:
  push:
    branches:
      - main
    paths:
    - '**.py'
    - '.github/workflows/lambda_deploy.yml'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-2
  LAMBDA_FUNCTION_NAME: OffsetTransactionsLambda
  LAMBDA_RUNTIME: python3.8

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd lambda
          pip3 install -r requirements.txt -t .
          zip -r deployment-package.zip .

      - name: AWS Lambda Deploy
        uses: appleboy/lambda-action@v0.1.5
        with:
          aws_access_key_id: ${AWS_ACCESS_KEY_ID}
          aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
          aws_region: ${{ AWS_REGION }}
          function_name: ${LAMBDA_FUNCTION_NAME}
          runtime: ${LAMBDA_RUNTIME}
          zip_file: lambda/deployment-package.zip
          handler: offset_transactions
